// ActionTypes to serve Book Requests
export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';

// Fetch Books for Search
export const SEARCH_BOOKS_REQUEST = 'SEARCH_BOOKS_REQUEST';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_FAILURE = 'SEARCH_BOOKS_FAILURE';

export const CLEAR_BOOK_LIST = 'CLEAR_BOOK_LIST';
export const UPDATE_BOOKS_LOADED = 'UPDATE_BOOKS_LOADED';
